using System.Collections.Generic;
using System.IO;
using System.Text;
using Tools.Logging;
using UnityEditor;
using UnityEngine;

namespace Logging.Editor
{
    internal static class LogApiGenerator
    {
        private static readonly HashSet<string> Keywords = new()
        {
            "abstract", "as", "base", "bool", "break", "byte", "case", "catch",
            "char", "checked", "class", "const", "continue", "decimal", "default",
            "delegate", "do", "double", "else", "enum", "event", "explicit",
            "extern", "false", "finally", "fixed", "float", "for", "foreach",
            "goto", "if", "implicit", "in", "int", "interface", "internal", "is",
            "lock", "long", "namespace", "new", "null", "object", "operator",
            "out", "override", "params", "private", "protected", "public",
            "readonly", "ref", "return", "sbyte", "sealed", "short", "sizeof",
            "stackalloc", "static", "string", "struct", "switch", "this", "throw",
            "true", "try", "typeof", "uint", "ulong", "unchecked", "unsafe",
            "ushort", "using", "virtual", "void", "volatile", "while"
        };

        public static void Generate(LoggingSettings settings, string generatedPath)
        {
            if (settings == null)
            {
                Debug.LogError("LoggingSettings is null.");
                return;
            }

            if (!TryValidate(settings, out var error))
            {
                Debug.LogError(error);
                return;
            }

            var directory = Path.GetDirectoryName(generatedPath);
            if (!string.IsNullOrEmpty(directory))
            {
                Directory.CreateDirectory(directory);
            }

            File.WriteAllText(generatedPath, BuildCode(settings), Encoding.UTF8);
            AssetDatabase.SaveAssets();
            AssetDatabase.ImportAsset(generatedPath);
            AssetDatabase.Refresh();
            Debug.Log($"Log API generated: {generatedPath}");
        }

        private static string BuildCode(LoggingSettings settings)
        {
            var builder = new StringBuilder();
            builder.AppendLine("// <auto-generated />");
            builder.AppendLine("// Generated by LoggingSettingsEditor. Do not edit manually.");
            builder.AppendLine();
            builder.AppendLine("using UnityEngine;");
            builder.AppendLine();
            builder.AppendLine("namespace Tools.Logging");
            builder.AppendLine("{");
            builder.AppendLine("    public static partial class Log");
            builder.AppendLine("    {");

            foreach (var channel in settings.Channels)
            {
                builder.Append("        public static readonly Logger ");
                builder.Append(channel.PropertyName);
                builder.Append(" = new Logger(\"");
                builder.Append(Escape(channel.Tag));
                builder.AppendLine("\");");
            }

            BuildInitializationMethod(builder, settings.Channels);

            builder.AppendLine("    }");
            builder.AppendLine("}");

            return builder.ToString();
        }

        private static bool TryValidate(LoggingSettings settings, out string error)
        {
            var propertyNames = new HashSet<string>();
            var tags = new HashSet<string>();

            foreach (var channel in settings.Channels)
            {
                if (channel == null)
                {
                    error = "Logging channel is null.";
                    return false;
                }

                if (!IsValidIdentifier(channel.PropertyName))
                {
                    error = $"Invalid log property name: '{channel.PropertyName}'. Example: Player, LevelManagement.";
                    return false;
                }

                if (string.IsNullOrWhiteSpace(channel.Tag))
                {
                    error = $"Log tag is empty for property '{channel.PropertyName}'.";
                    return false;
                }

                if (!propertyNames.Add(channel.PropertyName))
                {
                    error = $"Duplicate log property name: '{channel.PropertyName}'.";
                    return false;
                }

                if (!tags.Add(channel.Tag))
                {
                    error = $"Duplicate log tag: '{channel.Tag}'.";
                    return false;
                }
            }

            error = null;
            return true;
        }

        private static bool IsValidIdentifier(string value)
        {
            if (string.IsNullOrWhiteSpace(value))
            {
                return false;
            }

            if (Keywords.Contains(value))
            {
                return false;
            }

            if (!IsIdentifierStart(value[0]))
            {
                return false;
            }

            for (var i = 1; i < value.Length; i++)
            {
                if (!IsIdentifierPart(value[i]))
                {
                    return false;
                }
            }

            return true;
        }

        private static bool IsIdentifierStart(char value)
        {
            return value is '_' or >= 'A' and <= 'Z' or >= 'a' and <= 'z';
        }

        private static bool IsIdentifierPart(char value)
        {
            return IsIdentifierStart(value) || value is >= '0' and <= '9';
        }

        private static string Escape(string value)
        {
            return value.Replace("\\", @"\\").Replace("\"", "\\\"");
        }

        private static void BuildInitializationMethod(StringBuilder builder,
            IReadOnlyList<LogChannelDefinition> channels)
        {
            builder.AppendLine("\n        [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.BeforeSceneLoad)]");
            builder.AppendLine("        private static void InitLogging()");
            builder.AppendLine("        {");
            builder.AppendLine(
                "            var loggingSettings = Resources.Load<LoggingSettings>(LoggingSettings.FileName);");
            builder.AppendLine("            if (loggingSettings == null)");
            builder.AppendLine("            {");
            builder.AppendLine("                Error(\"No logging settings file found\");");
            builder.AppendLine("                return;");
            builder.AppendLine("            }");
            builder.AppendLine("\n            ApplySettings(loggingSettings);");
            builder.AppendLine("        }");

            builder.AppendLine("\n        private static void ApplySettings(LoggingSettings settings)");
            builder.AppendLine("        {");

            foreach (var channel in channels)
            {
                builder.AppendLine($"            {channel.PropertyName}.ApplySettings(settings);");
            }

            builder.AppendLine("        }");
        }
    }
}
