// <auto-generated />
// Generated by LoggingSettingsEditor. Do not edit manually.

using UnityEngine;

namespace Tools.Logging
{
    public static partial class Log
    {
        public static readonly Logger GameCycle = new Logger("GAME_CYCLE");
        public static readonly Logger CraneMechanic = new Logger("CRANE_MECHANIC");

        [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.BeforeSceneLoad)]
        private static void InitLogging()
        {
            var loggingSettings = Resources.Load<LoggingSettings>(LoggingSettings.FileName);
            if (loggingSettings == null)
            {
                Error("No logging settings file found");
                return;
            }

            ApplySettings(loggingSettings);
        }

        private static void ApplySettings(LoggingSettings settings)
        {
            GameCycle.ApplySettings(settings);
            CraneMechanic.ApplySettings(settings);
        }
    }
}
